### ISSUE TITLE
Adding a Metric from command line does not work as documented

### ISSUE THREAD

**Issue by rrowlands** [hobuinc/silvimetric#101]
When following the documentation I get the following unexpected error:

Traceback (most recent call last):
  File "/home/rrowlands/miniconda3/envs/silvimetric/bin/silvimetric", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/home/rrowlands/miniconda3/envs/silvimetric/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rrowlands/miniconda3/envs/silvimetric/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/rrowlands/miniconda3/envs/silvimetric/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rrowlands/miniconda3/envs/silvimetric/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rrowlands/miniconda3/envs/silvimetric/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rrowlands/miniconda3/envs/silvimetric/lib/python3.12/site-packages/click/decorators.py", line 45, in new_func
    return f(get_current_context().obj, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rrowlands/miniconda3/envs/silvimetric/lib/python3.12/site-packages/silvimetric/cli/cli.py", line 146, in initialize_cmd
    storageconfig = StorageConfig(tdb_dir = app.tdb_dir,
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 14, in __init__
  File "/home/rrowlands/miniconda3/envs/silvimetric/lib/python3.12/site-packages/silvimetric/resources/config.py", line 105, in __post_init__
    self.metric_definitions = { m.name: str(m) for m in self.metrics}
                                ^^^^^^
AttributeError: 'list' object has no attribute 'name'

**Comment by kylemann16** [comment]
Awesome, thanks for finding that. Can you point me to which line in the docs caused this to fail?

**Comment by rrowlands** [comment]
It's the initialize line in this section:

https://silvimetric.com/en/latest/tutorial.html#user-defined-metrics

**Comment by rrowlands** [comment]
I kind of suspect it's because this line:

https://github.com/hobuinc/silvimetric/blob/1454d5fe0f19e57982934632f030d5c2e82c4cbd/src/silvimetric/cli/common.py#L81

Is wrapping a list inside another list.

**Comment by rrowlands** [comment]
Tested and found to happen on versions 1.2.1 and also 1.2.3

**Comment by rrowlands** [comment]
It also seems like combining a custom metrics file with builtin metrics, as specified in the documentation, doesn't work. I'm getting this error:

Error: Invalid value for '--metrics' / '-m': Failed to import metrics from /home/rrowlands/dev/projects/uasdm/silvimetric/pg2/silvimetric_metrics.py.min,max,mean with error Failed to find import file for metrics at /home/rrowlands/dev/projects/uasdm/silvimetric/pg2/silvimetric_metrics.py.min,max,mean

When I get rid of the "min,max,mean" it works.

**Comment by kylemann16** [comment]
Yeah, that has changed once or twice through the development process. `-m "${METRIC_PATH},min,max,mean"` is supposed to work, as well as `-m $METRIC_PATH -m min -m max -m mean`. 

I'll take a look at this.

**Comment by kylemann16** [comment]
@rrowlands Hey just FYI, this issue plus a few others you submitted will be fixed in the next release, which is just waiting on a few things to get solidified. If you're interested in getting a working version earlier, you can `pip install` the main branch of `SilviMetric`. The documentation still has a few holes in it, but this issue plus #102 should both be fixed there.

**Comment by kylemann16** [comment]
I'm going to go ahead and close this issue. If this continues to be a problem for you, feel free to re open with more information
