### ISSUE TITLE
numpy AttributeError when running cli

### ISSUE THREAD

**Issue by JeremyScherer5** [hobuinc/silvimetric#105]
Fresh install on both win11 and ubuntu 22.04 results in the below error. Installed through pip and source. 

    Traceback (most recent call last):
    File "/home/jeremy/miniforge3/envs/silvimetric/bin/silvimetric", line 5, in <module>
        from silvimetric.cli.cli import cli
    File "/home/jeremy/miniforge3/envs/silvimetric/lib/python3.13/site-packages/silvimetric/__init__.py", line 15, in <module>
        from .commands.shatter import shatter
    File "/home/jeremy/miniforge3/envs/silvimetric/lib/python3.13/site-packages/silvimetric/commands/shatter.py", line 12, in <module>
        import dask.array as da
    File "/home/jeremy/miniforge3/envs/silvimetric/lib/python3.13/site-packages/dask/array/__init__.py", line 2, in <module>
        from dask.array import backends, fft, lib, linalg, ma, overlap, random
    File "/home/jeremy/miniforge3/envs/silvimetric/lib/python3.13/site-packages/dask/array/ma.py", line 8, in <module>
        from dask.array.routines import _average
    File "/home/jeremy/miniforge3/envs/silvimetric/lib/python3.13/site-packages/dask/array/routines.py", line 1569, in <module>
        @implements(np.round, np.round_)
                              ^^^^^^^^^
    File "/home/jeremy/miniforge3/envs/silvimetric/lib/python3.13/site-packages/numpy/__init__.py", line 400, in __getattr__
        raise AttributeError(
        ...<3 lines>...
        )
    AttributeError: `np.round_` was removed in the NumPy 2.0 release. Use `np.round` instead.

**Comment by kylemann16** [comment]
Thanks for the issue! I believe the next pull request will address this, as @j9ac9k accidentally stumbled on this as well when trying to set up a new environment.

**Comment by kylemann16** [comment]
@JeremyScherer5 Can you confirm if this is still a problem for you as of the release of `1.3.0`?

**Comment by JeremyScherer5** [comment]
Ran through the quickstart workflow with a fresh env and seems to be resolved, thank you for the quick fix fellas.

**Comment by kylemann16** [comment]
Excellent! Going to go ahead and close this then.
